remote_theme: jekyll/minima@3cdd14d
name: "Scott Onestak"
description: Scott Onestak GitHub Projects
title: "Scott Onestak"
header_pages:
  - Projects/Projects.md
  - aboutme.md
minima:
      social_links:
            linkedin: scott-onestak-a8917891
            instagram: scottonestak
            twitter: ScottOnestak
            github: ScottOnestak
google_analytics: UA-236997201-1
analytics:
  provider               : "google-gtag"
  google:
    measurement_id          : "G-L8GWFM8CEL"
    anonymize_ip         : # true, false (default)
