remote_theme: jekyll/minima
name: "Scott Onestak"
description: Scott Onestak GitHub Projects
title: null
minima:
      social_links:
            linkedin: scott-onestak-a8917891
            instagram: scottonestak
            twitter: ScottOnestak
