theme: minima 
name: "Scott Onestak"
description: Scott Onestak GitHub Projects
title: "Scott Onestak"
header_pages:
  - Projects/Projects.md
  - aboutme.md
minima:
      social_links:
            linkedin: scott-onestak-a8917891
            instagram: scottonestak
            twitter: ScottOnestak
google_analytics: UA-236997201-1
